export default defineEventHandler(async (event) => {
  // handle GET requests for the `api/movies` endpoint
  return [
    {
      id: "fb1",
      title: "Fantastic Beasts and Where to Find Them",
      summary:
        "Fantastic Beasts and Where to Find Them tells the tale of magizoologist Newton (Newt) Scamander and his adventure through New York City in the 1920s. A thrilling chase ensues when the magical creatures inside Newt’s suitcase are freed inside the city. Along with his new friends Jacob, a muggle, and Queenie, Newt must recapture all the creatures before they lay destruction to the city. However, things get complicated as a lurking Obscurial reveals itself and the Magical Congress of United States (MACUSA) intervenes.",
      directors: ["David Yates"],
      screenwriters: [],
      producers: [
        "David Heyman",
        "J. K. Rowling",
        "Steve Kloves",
        "Lionel Wigram",
      ],
      cinematographers: ["Philippe Rousselot"],
      editors: ["Mark Day"],
      distributors: ["Warner Bros. Pictures"],
      music_composers: ["James Newton Howard"],
      release_date: "10 November 2016",
      running_time: "133 minutes",
      budget: "$175-200 million",
      box_office: "$814 million",
      rating: "PG-13",
      trailer: "https://www.youtube.com/watch?v=Vso5o11LuGU",
      poster:
        "https://www.wizardingworld.com/images/products/films/rectangle-9.png",
      wiki: "https://harrypotter.fandom.com/wiki/Fantastic_Beasts_and_Where_to_Find_Them_(film)",
    },
    {
      id: "fb2",
      title: "Fantastic Beasts: The Crimes of Grindelwald",
      summary:
        "Fantastic Beasts: The Crimes of Grindelwald continues the story of Newt Scamander as he chases Credence Barebone on orders by Dumbledore, who suspects him to be Corvus Lestrange V. A twisted tale of vengeance and treachery unveils itself as the story advances and the true identity of Credence becomes even more obscure. Grindelwald’s plan to cause a war between muggles and wizards is set into motion, and Credence joins him.",
      directors: ["David Yates"],
      screenwriters: [],
      producers: [
        "David Heyman",
        "J. K. Rowling",
        "Steve Kloves",
        "Lionel Wigram",
      ],
      cinematographers: ["Philippe Rousselot"],
      editors: ["Mark Day"],
      distributors: ["Warner Bros. Pictures"],
      music_composers: ["James Newton Howard"],
      release_date: "16 November 2018",
      running_time: "134 minutes",
      budget: "$200 million",
      box_office: "$654.9 million",
      rating: "PG-13",
      trailer: "https://www.youtube.com/watch?v=8bYBOVWLNIs",
      poster:
        "https://www.wizardingworld.com/images/products/films/rectangle-10.png",
      wiki: "https://harrypotter.fandom.com/wiki/Fantastic_Beasts:_The_Crimes_of_Grindelwald",
    },
    {
      id: "fb3",
      title: "Fantastic Beasts: The Secrets of Dumbledore",
      summary:
        "The third movie in the Fantastic Beast Series sees Grindelwald trying to destroy the muggle world as Newt and his allies including Dumbledore try to stop him. Grindelwald kills a Qilin, a magical beast, to become the Supreme Leader of the ICW. Credence rethinks his decision to join Grindelwald upon realizing that he is the illegitimate son of Aberforth Dumbledore. The epic showdown takes place in Bhutan, where Dumbledore and Grindelwald fight it out after the blood pact that prevented them from dueling breaks. Grindelwald disapparates from the place and his plans are put to end.",
      directors: ["David Yates"],
      screenwriters: ["Steve Kloves"],
      producers: [
        "David Heyman",
        "J. K. Rowling",
        "Steve Kloves",
        "Lionel Wigram",
      ],
      cinematographers: ["George Richmond"],
      editors: ["Mark Day"],
      distributors: ["Warner Bros. Pictures"],
      music_composers: ["James Newton Howard"],
      release_date: "8 April 2022",
      running_time: "142 minutes",
      budget: "$200 million",
      box_office: "$379.8 million",
      rating: "PG-13",
      trailer: "https://www.youtube.com/watch?v=Y9dr2zw-TXQ",
      poster:
        "https://www.wizardingworld.com/images/products/films/rectangle-11.png",
      wiki: "https://harrypotter.fandom.com/wiki/Fantastic_Beasts:_The_Secrets_of_Dumbledore",
    },
    {
      id: "hp1",
      title: "Harry Potter and the Philosopher's Stone",
      summary:
        "Harry Potter’s dull life is completely changed on his eleventh birthday when a mysterious letter addressed to him arrives in the mail. After finding out about his real parents and a whole hidden wizarding world, he goes on to Hogwarts, his new magical school. From battling a troll to flying on broomsticks to catch golden snitches, Harry’s new life promises to be full of joy and adventure, until he finds out about a certain Dark Lord who murdered his parents is trying to regain power. With his friends Hermione and Ron, Harry sets out to find the philosopher’s stone before Voldemort to prevent his return. After advancing through a particularly difficult set of traps designed by the school, Harry faces the Dark Lord and manages to keep the Philosopher’s Stone safe.",
      directors: ["Chris Columbus"],
      screenwriters: ["Steve Kloves"],
      producers: ["Chris Columbus", "David Heyman", "Mark Radcliffe"],
      cinematographers: ["John Seale"],
      editors: ["Richard Francis-Bruce"],
      distributors: ["Warner Bros. Pictures"],
      music_composers: ["John Williams", "Conrad Pope"],
      release_date: "4 November 2001",
      running_time: "152 minutes",
      budget: "$125 million",
      box_office: "$1.018 million",
      rating: "PG",
      trailer: "https://www.youtube.com/watch?v=PbdM1db3JbY",
      poster:
        "https://www.wizardingworld.com/images/products/films/rectangle-1.png",
      wiki: "https://harrypotter.fandom.com/wiki/Harry_Potter_and_the_Philosopher's_Stone_(film)",
    },
    {
      id: "hp2",
      title: "Harry Potter and the Chamber of Secrets",
      summary:
        "Harry's second year at Hogwarts begins with a series of mishaps when he and Ron miss the train to Hogwarts. Furthermore, a mysterious Chamber of Secrets has been opened inside Hogwarts and students are getting petrified one after the another. Harry, Ron and Hermione start to uncover the dark tale behind the chamber using a diary Harry found, which leads them into the lair of an Acromantula. Ginny gets kidnapped and it is up to Harry to save her and the school from the monster of the Chamber of Secrets.",
      directors: ["Chris Columbus"],
      screenwriters: ["Steve Kloves"],
      producers: ["Chris Columbus", "David Heyman", "Mark Radcliffe"],
      cinematographers: ["Roger Pratt"],
      editors: ["Peter Honess"],
      distributors: ["Warner Bros. Pictures"],
      music_composers: ["John Williams", "William Ross", "Conrad Pope"],
      release_date: "15 November 2002",
      running_time: "161 minutes",
      budget: "$125 million",
      box_office: "$879.6 million",
      rating: "PG",
      trailer: "https://www.youtube.com/watch?v=2lSpGlsZtk0",
      poster:
        "https://www.wizardingworld.com/images/products/films/rectangle-2.png",
      wiki: "https://harrypotter.fandom.com/wiki/Harry_Potter_and_the_Chamber_of_Secrets_(film)",
    },
  ];
});
